---
# role: postgresql
# file: tasks/main.yml

- name: "POSTGRESQL | Ensure required facts are available"
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - os_family
  when: (ansible_facts | default({})).get('os_family') is none
  tags:
    - postgresql_facts

- name: "POSTGRESQL | Include platform variables"
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_facts.os_family }}.yml"
  tags:
    - postgresql_vars

- name: "POSTGRESQL | Assert inputs"
  ansible.builtin.import_tasks: assert.yml

- name: "POSTGRESQL | Manage packages"
  ansible.builtin.package:
    name: "{{ __postgresql_packages }}"
    state: present
  tags:
    - postgresql_install

- name: "POSTGRESQL | Ensure cluster exists"
  ansible.builtin.import_tasks: pg_cluster.yml
  tags:
    - postgresql_cluster

- name: "POSTGRESQL | Inspect runtime before configuring PostgreSQL"
  ansible.builtin.import_tasks: pg_runtime.yml
  tags:
    - postgresql_config

- name: "POSTGRESQL | Configure PostgreSQL"
  ansible.builtin.import_tasks: pg_config.yml
  tags:
    - postgresql_config

- name: "POSTGRESQL | Configure identity mapping"
  ansible.builtin.import_tasks: pg_ident.yml
  tags:
    - postgresql_pg_ident

- name: "POSTGRESQL | Configure host-based authentication"
  ansible.builtin.import_tasks: pg_hba.yml
  tags:
    - postgresql_pg_hba

- name: "POSTGRESQL | Manage service"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    enabled: true
    state: started
  tags:
    - postgresql_service

- name: "POSTGRESQL | Apply pending configuration changes"
  ansible.builtin.meta: flush_handlers
  tags:
    - postgresql_config

- name: "POSTGRESQL | Manage runtime objects"
  ansible.builtin.import_tasks: pg_objects.yml
  tags:
    - postgresql_objects
