---
# role: postgresql
# file: tasks/main.yml

- name: "PostgreSQL | Ensure required facts are available"
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - os_family
  when: (ansible_facts | default({})).get('os_family') is none
  tags:
    - postgresql_facts

- name: "PostgreSQL | Include platform variables"
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_facts['os_family'] }}.yml"
  tags:
    - postgresql_vars

- name: "PostgreSQL | Assert inputs"
  ansible.builtin.import_tasks: assert.yml

- name: "PostgreSQL | Manage packages"
  ansible.builtin.package:
    name: "{{ __postgresql_packages }}"
    state: present
  tags:
    - postgresql_install

- name: "PostgreSQL | Ensure cluster exists"
  ansible.builtin.import_tasks: cluster.yml
  tags:
    - postgresql_cluster

- name: "PostgreSQL | Configure PostgreSQL"
  ansible.builtin.import_tasks: config.yml
  tags:
    - postgresql_config

- name: "PostgreSQL | Configure identity mapping"
  ansible.builtin.import_tasks: pg_ident.yml
  tags:
    - postgresql_pg_ident

- name: "PostgreSQL | Configure host-based authentication"
  ansible.builtin.import_tasks: pg_hba.yml
  tags:
    - postgresql_pg_hba

- name: "PostgreSQL | Manage service"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    enabled: true
    state: started
  tags:
    - postgresql_service

- name: "PostgreSQL | Apply pending configuration changes"
  ansible.builtin.meta: flush_handlers
  tags:
    - postgresql_config

- name: "PostgreSQL | Manage runtime objects"
  ansible.builtin.import_tasks: objects.yml
  when: >
    postgresql_roles | length > 0 or
    postgresql_memberships | length > 0 or
    postgresql_tablespaces | length > 0 or
    postgresql_databases | length > 0 or
    postgresql_extensions | length > 0 or
    postgresql_publications | length > 0 or
    postgresql_subscriptions | length > 0
  tags:
    - postgresql_objects
