---
# role: postgresql
# file: tasks/pg_hba.yml

- name: "POSTGRESQL | Configure pg_hba.conf"
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ __postgresql_config_dir }}/pg_hba.conf"
    owner: "{{ __postgresql_user }}"
    group: "{{ __postgresql_group }}"
    mode: "0640"
    backup: true
  notify: apply configuration
  no_log: "{{ postgresql_no_log | bool }}"
