---
# role: postgresql
# file: tasks/pg_ident.yml

- name: "POSTGRESQL | Configure pg_ident.conf"
  ansible.builtin.template:
    src: pg_ident.conf.j2
    dest: "{{ __postgresql_config_dir }}/pg_ident.conf"
    owner: "{{ __postgresql_user }}"
    group: "{{ __postgresql_group }}"
    mode: "0640"
    backup: true
  notify: Apply postgresql configuration
  no_log: "{{ postgresql_no_log | bool }}"
