---
# role: postgresql
# file: handlers/main.yml

- name: "Validate postgresql configuration"
  ansible.builtin.command:
    cmd: >-
      {{ __postgresql_bin_dir }}/postgres
      -D {{ __postgresql_data_dir }}
      -C config_file
      -c config_file={{ __postgresql_config_dir }}/postgresql.conf
  become: true
  become_user: "{{ __postgresql_user }}"
  changed_when: false
  tags:
    - postgresql_validate

- name: "Reload postgresql"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    state: reloaded
  tags:
    - postgresql_service

- name: "Restart postgresql"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    state: restarted
  tags:
    - postgresql_service
