---
# role: jomrr.postgresql
# file: handlers/main.yml

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: "Restart postgresql"
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: restarted
    enabled: true
