---
# role: postgresql
# file: handlers/main.yml

- name: "POSTGRESQL | Reload configuration"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    state: reloaded
  listen: Apply postgresql configuration
  when:
    - __postgresql_running
    - not ansible_check_mode

- name: "POSTGRESQL | Read pending restart requirements"
  become: true
  become_user: "{{ __postgresql_user }}"
  community.postgresql.postgresql_query:
    login_db: postgres
    login_user: postgres
    login_port: "{{ __postgresql_login_port }}"
    login_unix_socket: "{{ __postgresql_login_socket }}"
    query: SELECT count(*) AS pending FROM pg_settings WHERE pending_restart
  register: __postgresql_pending_restart
  changed_when: false
  listen: Apply postgresql configuration
  when:
    - __postgresql_running
    - not ansible_check_mode

- name: "POSTGRESQL | Restart when PostgreSQL requires it"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    state: restarted
  listen: Apply postgresql configuration
  when:
    - __postgresql_running
    - not ansible_check_mode
    - __postgresql_extra_restart_result is changed or __postgresql_pending_restart.query_result[0].pending | int > 0
