---
# role: postgresql
# file: handlers/main.yml

- name: "Validate postgresql configuration"
  ansible.builtin.command:
    cmd: >-
      {{ __postgresql_bin_dir }}/postgres
      -D {{ __postgresql_data_dir }}
      -C config_file
      -c config_file={{ __postgresql_config_dir }}/postgresql.conf
  become: true
  become_user: "{{ __postgresql_user }}"
  changed_when: false
  tags:
    - postgresql_validate

- name: "Mark postgresql restart required"
  ansible.builtin.set_fact:
    __postgresql_restart_required: true
  changed_when: false
  tags:
    - postgresql_service

- name: "Apply postgresql configuration"
  ansible.builtin.service:
    name: "{{ __postgresql_service_name }}"
    state: "{{ 'restarted' if __postgresql_restart_required | default(false) | bool else 'reloaded' }}"
  tags:
    - postgresql_service
