---
# role: postgresql
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        postgresql_port: 5433
        postgresql_shared_buffers: "128MB"
        postgresql_effective_cache_size: "512MB"
        postgresql_work_mem: "4MB"
        postgresql_maintenance_work_mem: "64MB"
        postgresql_autovacuum_work_mem: "64MB"
        postgresql_temp_file_limit: "256MB"
        postgresql_max_worker_processes: 2
        postgresql_max_parallel_workers: 1
        postgresql_max_wal_size: "512MB"
        postgresql_min_wal_size: "80MB"
        postgresql_roles:
          - name: "app"
            role_attr_flags: "LOGIN"
        postgresql_databases:
          - name: "appdb"
            owner: "app"
            encoding: "UTF8"
        postgresql_extensions:
          - name: "pgcrypto"
            database: "appdb"
verifier:
  name: "ansible"
scenario:
  name: "dev"
platforms:
  - name: almalinux-latest-postgresql
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: debian-latest-postgresql
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: fedora-latest-postgresql
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-leap-latest-postgresql
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-tumbleweed-latest-postgresql
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: ubuntu-latest-postgresql
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: true
