---
# role: postgresql
# file: molecule/resources/playbooks/converge.yml

- name: "POSTGRESQL | Converge PostgreSQL"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
