---
# role: ansible-role-postgresql
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: molecule/tox/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: postgresql-${TOX_ENVNAME:-"default"}
    image: "${uns:-jam82}/molecule-${img:-debian}:${tag:-latest}"
    command: ""
    pre_build_image: true
    privileged: false
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        postgresql_role_enabled: true
verifier:
  name: ansible
